name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build docker image
      run: docker build . --file Dockerfile --tag sut:latest
      
    - uses: addnab/docker-run-action@v3
      with:
        image: sut:latest
        run: echo "hello world"
      
    
